Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-08, with the labels that each got.

#109 support multiple expected results in test files
  pkg/testutil/testutil.go
Labels: approved, cncf-cla: yes, needs-triage, size/M

#110 Support filtering metrics using the cluster name
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/operations.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm

#111 switch clusterName filter to be a slice
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/operations.go
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#114 Adding support for network usage metrics collection
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/testdata/collector/containers-builtin-app-network-utilization/expected.txt
  pkg/collector/testdata/collector/containers-builtin-app-network-utilization/input_client_objects.yaml
  pkg/collector/testdata/collector/containers-builtin-app-network-utilization/input_collector_spec.yaml
  pkg/collector/testdata/collector/containers-builtin-app-network-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-network-utilization/input_usage.yaml
  pkg/collector/testdata/values/container/expected.yaml
  pkg/collector/testdata/values/container/input.yaml
  pkg/collector/values.go
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#115 Sampler to properly format ipv6 address when a collector self-registers
  pkg/sampler/server.go
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#116 Sampler check connections aren't already shutdown before stopping them
  pkg/sampler/server.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage

#118 Fixup config for sampler and collector
  README.md
  config/kustomization.yaml
  config/metrics-node-sampler/configmaps/sampler.yaml
  config/metrics-node-sampler/sampler.daemonset.yaml
  config/metrics-prometheus-collector/collector.deployment.yaml
  config/metrics-prometheus-collector/configmaps/collector.yaml
  config/prometheus/configmaps/prometheus.yml
  pkg/sampler/ctrstats_linux_amd64.go
Labels: size/L, approved, cncf-cla: yes, needs-triage
