Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-04, with the labels that each got.

#48 Refactor constants into types for clarity's sake
  go.mod
  go.sum
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/builtin_labels.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/labels.go
  pkg/collector/local.go
  pkg/collector/metric.go
  pkg/collector/types.go
  pkg/collector/values.go
Labels: ok-to-test, approved, cncf-cla: yes, triage/accepted, size/XL, lgtm

#49 Remove schedule_time and schedule_wait_time resources
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/testdata/collector/items/expected.txt
  pkg/collector/values.go
Labels: ok-to-test, approved, cncf-cla: yes, needs-triage, lgtm, size/M

#53 fix bug in metrics_prometheus_collector_registered_count metric
  pkg/collector/collector.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage

#55 Publish scheduler_recent_time_seconds metric
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/testdata/collector/items/expected.txt
  pkg/collector/testdata/collector/items/input_client_objects.yaml
  pkg/collector/testdata/collector/items/input_collector_spec.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-yet/expected.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-yet/input.yaml
  pkg/collector/testdata/values/scheduler-previously-scheduled/expected.yaml
  pkg/collector/testdata/values/scheduler-previously-scheduled/input.yaml
  pkg/collector/testdata/values/scheduler-recently-scheduled/expected.yaml
  pkg/collector/testdata/values/scheduler-recently-scheduled/input.yaml
  pkg/collector/values.go
Labels: size/L, ok-to-test, approved, cncf-cla: yes, needs-triage, lgtm

#56 Clean up collector register with nodes metrics
  pkg/collector/collector.go
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#51 Fix typo order error for the Readme.md
  README.md
Labels: size/XS, approved, cncf-cla: yes, triage/accepted, lgtm

#59 fix collector waitgroup for caching
  pkg/collector/collector.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage

#60 Parse total_rss and total_cache for cgroup memory samples
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-node-sampler/integration/testdata/input_samples.yaml
  pkg/api/samplerserverv1alpha1/doc.go
  pkg/sampler/cgroup.go
Labels: ok-to-test, approved, cncf-cla: yes, needs-triage, lgtm, size/M

#61 Refine scheduler health metrics
  .gitignore
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/testdata/collector/items/expected.txt
  pkg/collector/testdata/collector/items/input_collector_spec.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-1/expected.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-1/input.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-2/expected.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-2/input.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-yet/expected.yaml
  pkg/collector/testdata/values/scheduler-not-scheduled-yet/input.yaml
  pkg/collector/testdata/values/scheduler-recently-scheduled/expected.yaml
  pkg/collector/testdata/values/scheduler-recently-scheduled/input.yaml
  pkg/collector/testdata/values/scheduler-scheduled-1/expected.yaml
  pkg/collector/testdata/values/scheduler-scheduled-1/input.yaml
  pkg/collector/testdata/values/scheduler-scheduled-2/expected.yaml
  pkg/collector/testdata/values/scheduler-scheduled-2/input.yaml
  pkg/collector/testdata/values/scheduler-scheduled-3/expected.yaml
  pkg/collector/testdata/values/scheduler-scheduled-3/input.yaml
  pkg/collector/types.go
  pkg/collector/values.go
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#63 Fix check on checkCreatedPodFrequency
  pkg/sampler/server.go
Labels: size/XS, cncf-cla: yes, needs-triage, lgtm

#67 Collector exit after leadership loss
  cmd/metrics-prometheus-collector/cmd/cmd.go
Labels: approved, cncf-cla: yes, needs-triage, size/M

#68 Expose pprof endpoints on metrics-node-sampler
  cmd/metrics-node-sampler/cmd/cmd.go
  pkg/sampler/server.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm

#69 Tweak collector exit after leadership loss
  cmd/metrics-prometheus-collector/cmd/cmd.go
Labels: approved, cncf-cla: yes, needs-triage, size/M

#70 Stop parsing container annotations, extract info from labels
  cmd/container-monitor/cmd/cmd.go
  cmd/metrics-node-sampler/cmd/cmd_linux_amd64.go
  pkg/ctrstats/ctrstats.go
  pkg/sampler/ctrstats_linux_amd64.go
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#71 Create a protobuf client for metrics-node-sampler
  cmd/metrics-node-sampler-client/main.go
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M
