Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-02, with the labels that each got.

#27 Support for archiving to GCS and BigQuery
  Dockerfile
  Makefile
  README.md
  cmd/umc-archiver/cmds/main.go
  cmd/umc-archiver/main.go
  config/kustomization.yaml
  config/metrics-node-sampler/configmaps/sampler.yaml
  config/metrics-node-sampler/sampler.daemonset.yaml
  config/metrics-prometheus-collector/collector.deployment.yaml
  config/metrics-prometheus-collector/configmaps/collector.yaml
  config/prometheus/configmaps/prometheus.yml
  config/prometheus/prometheus.deployment.yaml
  go.mod
  go.sum
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#28 remove dead code
  pkg/collector/values.go
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#33 remove dead code: extension labels
  pkg/collector/extension_labels.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm
