Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-01, with the labels that each got.

#3 Configs for kind
  Dockerfile
  Makefile
  README.md
  config/grafana/configmaps/grafana.yml
  config/grafana/grafana.deployment.yaml
  config/grafana/grafana.service.yaml
  config/grafana/kustomization.yaml
  config/kustomization.yaml
  config/metrics-node-sampler/configmaps/sampler.yaml
  config/metrics-node-sampler/kustomization.yaml
  config/metrics-node-sampler/sampler.daemonset.yaml
  config/metrics-node-sampler/sampler.service.yaml
  config/metrics-node-sampler/sampler.serviceaccount.yaml
  config/metrics-prometheus-collector/collector.deployment.yaml
  config/metrics-prometheus-collector/collector.role.yaml
  config/metrics-prometheus-collector/collector.rolebinding.yaml
  config/metrics-prometheus-collector/collector.service.yaml
  config/metrics-prometheus-collector/collector.serviceaccount.yaml
  config/metrics-prometheus-collector/configmaps/collector.yaml
  config/metrics-prometheus-collector/kustomization.yaml
  config/namespace.yaml
  config/prometheus/configmaps/prometheus.yml
  config/prometheus/kustomization.yaml
  config/prometheus/prometheus.deployment.yaml
  config/prometheus/prometheus.service.yaml
  config/prometheus/prometheus.serviceaccount.yaml
Labels: approved, cncf-cla: yes, size/XL, needs-triage, lgtm

#6 Support for saving metrics locally to json files
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/local.go
  pkg/collector/testdata/collector-save/aggregatedsamples_0/expected.json
  pkg/collector/testdata/collector-save/aggregatedsamples_1/expected.json
  pkg/collector/testdata/collector-save/aggregatedsamples_2/expected.json
  pkg/collector/types.go
  pkg/testutil/testutil.go
Labels: size/L, approved, cncf-cla: yes, needs-triage

#7 Add a "verify" target to makefile, including license header verification
  Makefile
  cmd/container-monitor/main.go
  cmd/metrics-node-sampler/cmd/cmd.go
  cmd/metrics-node-sampler/cmd/cmd_linux_amd64.go
  cmd/metrics-node-sampler/cmd/cmd_others.go
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-node-sampler/main.go
  cmd/metrics-prometheus-collector/cmd/cmd.go
  cmd/metrics-prometheus-collector/integration/integration_test.go
  cmd/metrics-prometheus-collector/main.go
  cmd/test-app/main.go
  pkg/api/collectorcontrollerv1alpha1/doc.go
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/api/doc.go
  pkg/api/quotamanagementv1alpha1/doc.go
  pkg/api/quotamanagementv1alpha1/groupversion_info.go
  pkg/api/quotamanagementv1alpha1/types.go
  pkg/api/samplerserverv1alpha1/doc.go
  pkg/api/samplerserverv1alpha1/types.go
  pkg/api/samplerserverv1alpha1/types_test.go
  pkg/collector/builtin_labels.go
  pkg/collector/cache.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/doc.go
  pkg/collector/extension_labels.go
  pkg/collector/labels.go
  pkg/collector/local.go
  pkg/collector/metric.go
  pkg/collector/operations.go
  pkg/collector/types.go
  pkg/collector/util.go
  pkg/collector/utilization/sampler_collector.go
  pkg/collector/values.go
  pkg/ctrstats/ctrstats.go
  pkg/ctrstats/metrics.go
  pkg/log/log.go
  pkg/sampler/cache.go
  pkg/sampler/cgroup.go
  pkg/sampler/ctrstats_linux_amd64.go
  pkg/sampler/ctrstats_others.go
  pkg/sampler/doc.go
  pkg/sampler/server.go
  pkg/sampler/types.go
  pkg/scheme/scheme.go
  pkg/testutil/example_testutil_test.go
  pkg/testutil/fakeclient.go
  pkg/testutil/integrationutil.go
  pkg/testutil/testutil.go
  pkg/version/version.go
  pkg/watchconfig/watchconfig.go
  tools/tools.go
Labels: approved, cncf-cla: yes, triage/accepted, size/XL, kind/cleanup

#12 Increase threshold for failure in collector integration test
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-prometheus-collector/integration/integration_test.go
  pkg/testutil/integrationutil.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage

#13 Support for statically defining metrics exported by the collector
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/testdata/collector/sidecar/expected.txt
  pkg/collector/testdata/collector/sidecar/input_1_sidecar_config.json
  pkg/collector/testdata/collector/sidecar/input_2_sidecar_config.json
  pkg/collector/testdata/collector/sidecar/input_client_objects.yaml
  pkg/collector/testdata/collector/sidecar/input_collector_spec.yaml
  pkg/collector/testdata/collector/sidecar/input_ignore_metric_names.txt
Labels: size/L, approved, cncf-cla: yes, needs-triage

#14 Split out unit test results with junit/XML
  .gitignore
  Makefile
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#15 Adding missing label code (20-99)
  cmd/metrics-node-sampler/cmd/cmd_others.go
  pkg/collector/capacity_test.go
  pkg/collector/extension_labels.go
  pkg/collector/labels.go
  pkg/collector/local.go
  pkg/sampler/cgroup.go
Labels: approved, cncf-cla: yes, size/XL, needs-triage

#16 Configuration options for labels
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/collector.go
  pkg/collector/extension_labels.go
  pkg/collector/testdata/collector/sidecar/expected.txt
  pkg/collector/testdata/collector/sidecar/input_1_sidecar_config.json
  pkg/collector/testdata/collector/sidecar/input_collector_spec.yaml
  pkg/collector/types.go
Labels: size/L, approved, cncf-cla: yes, needs-triage

#17 make container-monitor vendable
  cmd/container-monitor/cmd/cmd.go
  cmd/container-monitor/main.go
  go.mod
  go.sum
Labels: size/L, approved, cncf-cla: yes, needs-triage

#18 Add verify/update targets for generated code
  Makefile
  pkg/collector/api/api.pb.go
  pkg/sampler/api/api.pb.go
  pkg/sampler/api/api_grpc.pb.go
  tools/install-protoc.sh
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#22 go.mod / Dockerfile: Modernize deps
  Dockerfile
  go.mod
  go.sum
Labels: ok-to-test, approved, cncf-cla: yes, size/XL, needs-triage, lgtm

#23 add max observed minus used to valid quota sources
  pkg/api/collectorcontrollerv1alpha1/types.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm

#26 Add metric sample
  METRICS.md
  README.md
Labels: size/L, ok-to-test, approved, cncf-cla: yes, triage/accepted, lgtm

#25 metrics-prometheus-collector: Add leases to ClusterRole
  README.md
  config/metrics-prometheus-collector/collector.role.yaml
Labels: size/XS, ok-to-test, approved, cncf-cla: yes, triage/accepted, lgtm

#24 Improve tooling installation
  pkg/collector/api/api.pb.go
  pkg/sampler/api/api.pb.go
  pkg/sampler/api/api.pb.gw.go
  tools/go.mod
  tools/go.sum
  tools/install.sh
  tools/tools.go
Labels: ok-to-test, approved, cncf-cla: yes, triage/accepted, size/XL, lgtm
