Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-07, with the labels that each got.

#99 Cleanup metrics-node-sampler code
  pkg/api/samplerserverv1alpha1/testdata/default/empty/expected.yaml
  pkg/api/samplerserverv1alpha1/testdata/default/values/expected.yaml
  pkg/api/samplerserverv1alpha1/types.go
  pkg/sampler/server.go
  pkg/testutil/integrationutil.go
Labels: approved, cncf-cla: yes, triage/accepted, size/XL

#102 Delete node-sampler pods from the collector if we can't register with…
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/collector.go
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#100 Add "network" fields to the ContainerMetrics proto
  cmd/metrics-node-sampler/integration/testdata/basic/expected.json
  cmd/metrics-node-sampler/integration/testdata/prune-values/expected.json
  pkg/sampler/api/api.pb.go
  proto/pkg/sampler/api/api.proto
Labels: size/L, ok-to-test, approved, cncf-cla: yes, needs-triage, lgtm

#104 Fix collector deleting sampler pods
  pkg/collector/collector.go
Labels: size/S, approved, cncf-cla: yes, needs-triage

#105 Disable TaintNodesByCondition admission plugin for integration tests
  pkg/testutil/integrationutil.go
  pkg/testutil/testutil_test.go
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#106 Support for image_name container label
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/builtin_labels.go
  pkg/collector/testdata/collector/containers-builtin-deployment/expected.txt
  pkg/collector/testdata/collector/containers-builtin-deployment/input_collector_spec.yaml
  pkg/collector/testdata/collector/items/expected.txt
  pkg/collector/testdata/collector/items/input_collector_spec.yaml
  pkg/collector/testdata/labels/container/builtin-scheduled/expected.yaml
  pkg/collector/testdata/labels/container/builtin-scheduled/input.yaml
  pkg/collector/testdata/values/container/expected.yaml
  pkg/collector/values.go
Labels: size/L, approved, cncf-cla: yes, needs-triage

#103 The initial stub at adding support for cAdvisor
  cmd/metrics-node-sampler/integration/testdata/basic/expected.json
  cmd/metrics-node-sampler/integration/testdata/prune-values/expected.json
  go.mod
  go.sum
  pkg/api/samplerserverv1alpha1/testdata/default/empty/expected.yaml
  pkg/api/samplerserverv1alpha1/testdata/default/values/expected.yaml
  pkg/api/samplerserverv1alpha1/testdata/default/values/input.yaml
  pkg/api/samplerserverv1alpha1/types.go
  pkg/cadvisor/api/cadvisor.pb.go
  pkg/cadvisor/api/cadvisor.pb.gw.go
  pkg/cadvisor/api/cadvisor_grpc.pb.go
  pkg/cadvisor/cadvisor.go
  pkg/sampler/cache.go
  pkg/sampler/cache_test.go
  pkg/sampler/server.go
  pkg/sampler/types.go
Labels: ok-to-test, approved, size/XXL, cncf-cla: yes, needs-triage, lgtm

#107 Extend testutil to automatically compare objects, events and metrics.
  pkg/testutil/testutil.go
Labels: size/L, approved, cncf-cla: yes, needs-triage
