Repository kubernetes-sigs/usage-metrics-collector, pull requests merged in 2023-05, with the labels that each got.

#72 optimize collector caching of metrics response
  cmd/metrics-prometheus-collector/cmd/cmd.go
  cmd/metrics-prometheus-collector/integration/integration_test.go
  cmd/metrics-prometheus-collector/integration/testdata/basic/input_collector.yaml
  cmd/metrics-prometheus-collector/integration/testdata/over-max-extension-labels/input_collector.yaml
  cmd/metrics-prometheus-collector/integration/testdata/rqd-features/input_collector.yaml
  config/metrics-prometheus-collector/configmaps/collector.yaml
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/collector.go
  pkg/collector/types.go
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#74 Code cleanup
  cmd/metrics-prometheus-collector/cmd/cmd.go
  pkg/collector/collector.go
  pkg/collector/testdata/collector-override/override/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/cluster-scoped-annotations-multiple/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/cluster-scoped-annotations/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/collector-funcs/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-throttle-oom/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization-operations/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-requests-minus-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-utilization-succeeded-failed/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-memory-requests-minus-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-memory-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-deployment/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-namespace/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-replicaset/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-workload-override/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-workload/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-extensions-node/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-filter-exclude/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-filter-include/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-histogram-sum/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-histogram/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-sum-histogram/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/items/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/namespace-extensions/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node-level-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node-taints/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/pvs_pvcs/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/pvs_pvcs_multi_bind/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/quota-use-name/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/quota/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/resource-quota-descriptor/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/sidecar/input_ignore_metric_names.txt
Labels: size/L, approved, cncf-cla: yes, needs-triage

#75 Add names to aggregation and levels and publish metric aggregation times
  cmd/metrics-prometheus-collector/cmd/cmd.go
  cmd/metrics-prometheus-collector/integration/integration_test.go
  cmd/metrics-prometheus-collector/integration/testdata/basic/input_ignore_metric_names.txt
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/operations.go
  pkg/collector/testdata/collector-override/override/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/aggregatedsamples_0/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/aggregatedsamples_1/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/aggregatedsamples_2/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/cgroup/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/container/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/node/input_ignore_metric_names.txt
  pkg/collector/testdata/collector-save/quota/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/cluster-scoped-annotations-multiple/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/cluster-scoped-annotations/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/collector-funcs/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-throttle-oom/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization-operations/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-requests-minus-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-utilization-succeeded-failed/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-memory-requests-minus-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app-memory-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-app/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-deployment/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-namespace/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-replicaset/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-workload-override/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-builtin-workload/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-extensions-node/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-filter-exclude/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-filter-include/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-histogram-sum/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-histogram/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-sum-histogram/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/items/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/namespace-extensions/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node-level-utilization/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node-taints/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/node/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/pvs_pvcs/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/pvs_pvcs_multi_bind/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/quota-use-name/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/quota/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/resource-quota-descriptor/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/sidecar/input_ignore_metric_names.txt
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#73 Add Collector benchmark
  pkg/collector/capacity_test.go
  pkg/testutil/integrationutil.go
  pkg/testutil/testutil.go
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#76 Collector wait until has cached result with utilization metrics before
  cmd/metrics-prometheus-collector/cmd/cmd.go
  pkg/collector/utilization/sampler_collector.go
Labels: size/S, approved, cncf-cla: yes, needs-triage

#77 optimize locally metrics save to run asynchronously after completing …
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/capacity_test.go
  pkg/collector/collector.go
  pkg/collector/operations.go
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm

#78 Fix phase name in collection time metric
  pkg/collector/collector.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm

#79 Improve performance of aggregateMetric function
  pkg/collector/operations.go
Labels: size/S, approved, cncf-cla: yes, needs-triage, lgtm

#80 node-sampler to publish per-container / cgroup aggregated mean
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-node-sampler/integration/testdata/expected.json
  cmd/metrics-node-sampler/integration/testdata/input_samples.yaml
  pkg/sampler/api/api.pb.go
  pkg/sampler/cache.go
  pkg/sampler/server.go
  pkg/sampler/types.go
  proto/pkg/sampler/api/api.proto
Labels: size/L, approved, cncf-cla: yes, needs-triage

#82 Expose metrics for "avg" values provided by node-sampler
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-node-sampler/integration/testdata/expected.json
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/api/samplerserverv1alpha1/types.go
  pkg/collector/collector.go
  pkg/collector/collector_test.go
  pkg/collector/testdata/collector-override/override/input_usage.yaml
  pkg/collector/testdata/collector-save/container/expected.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-throttle-oom/expected.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-throttle-oom/input_usage.yaml
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization-operations/expected.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization-operations/input_usage.yaml
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/expected.txt
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/input_collector_spec.yaml
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/input_usage.yaml
  pkg/collector/testdata/collector/node-level-utilization/expected.txt
  pkg/collector/testdata/collector/node-level-utilization/input_collector_spec.yaml
  pkg/collector/testdata/collector/node-level-utilization/input_usage.yaml
  pkg/collector/testdata/values/container/expected.yaml
  pkg/collector/testdata/values/container/input.yaml
  pkg/collector/types.go
  pkg/collector/values.go
  pkg/sampler/api/api.pb.go
  pkg/sampler/cache.go
  pkg/sampler/server.go
  pkg/sampler/types.go
  proto/pkg/sampler/api/api.proto
Labels: approved, cncf-cla: yes, size/XL, needs-triage, lgtm

#81 Document available collection performance metrics
  README.md
  docs/performance-analysis.md
Labels: approved, cncf-cla: yes, needs-triage, lgtm, size/M

#83 Support source alias' in metric names
  pkg/api/collectorcontrollerv1alpha1/types.go
  pkg/collector/collector.go
  pkg/collector/metric.go
  pkg/collector/testdata/collector/containers-source-alias/expected.txt
  pkg/collector/testdata/collector/containers-source-alias/input_client_objects.yaml
  pkg/collector/testdata/collector/containers-source-alias/input_collector_spec.yaml
  pkg/collector/testdata/collector/containers-source-alias/input_ignore_metric_names.txt
  pkg/collector/testdata/collector/containers-source-alias/input_usage.yaml
Labels: size/L, approved, cncf-cla: yes, needs-triage

#85 Fix divide by 0 panic in collector operations
  pkg/collector/operations.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage, lgtm

#86 Fix div-by-0 panic
  pkg/collector/operations.go
Labels: size/XS, approved, cncf-cla: yes, needs-triage

#88 Fix memory units for avg_utilization
  pkg/collector/testdata/collector/containers-builtin-app-cpu-memory-utilization/expected.txt
  pkg/collector/testdata/values/container/expected.yaml
  pkg/collector/values.go
Labels: size/S, approved, cncf-cla: yes, needs-triage

#93 Drop anomalous values from metrics-node-sampler avg
  cmd/metrics-node-sampler/integration/integration_test.go
  cmd/metrics-node-sampler/integration/testdata/basic/expected.json
  cmd/metrics-node-sampler/integration/testdata/basic/input_samples.yaml
  cmd/metrics-node-sampler/integration/testdata/basic/input_test.yaml
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpu/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpu/kubelet/kubepods/burstable/podpod12345/abcdef/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpu/system.slice/kubelet.service/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/kubelet/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/kubelet/kubepods/burstable/podpod12345/abcdef/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/kubelet/kubepods/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/kubelet/kubepods/guaranteed/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/max.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/min.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/system.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/cpuacct/system.slice/kubelet.service/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.failcnt
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.oom_control
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/kubelet/kubepods/guaranteed/memory.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/kubelet/kubepods/memory.stat
  cmd/metrics-node-sampler/integration/testdata/basic/sys/fs/cgroup/memory/system.slice/kubelet.service/memory.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/expected.json
  cmd/metrics-node-sampler/integration/testdata/prune-values/input_samples.yaml
  cmd/metrics-node-sampler/integration/testdata/prune-values/input_test.yaml
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpu/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpu/kubelet/kubepods/burstable/podpod12345/abcdef/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpu/system.slice/kubelet.service/cpu.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/kubelet/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/kubelet/kubepods/burstable/podpod12345/abcdef/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/kubelet/kubepods/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/kubelet/kubepods/guaranteed/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/max.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/min.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/system.slice/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/cpuacct/system.slice/kubelet.service/cpuacct.usage
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.failcnt
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.oom_control
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/kubelet/kubepods/burstable/podpod12345/abcdef/memory.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/kubelet/kubepods/guaranteed/memory.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/kubelet/kubepods/memory.stat
  cmd/metrics-node-sampler/integration/testdata/prune-values/sys/fs/cgroup/memory/system.slice/kubelet.service/memory.stat
  pkg/api/samplerserverv1alpha1/types.go
  pkg/sampler/cache.go
  pkg/sampler/server.go
Labels: size/L, approved, cncf-cla: yes, needs-triage, lgtm
